lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_2_addon/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import index


urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list_json, friend_list, next_mahasiswa_list, \
    prev_mahasiswa_list

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-friend/$', add_friend, name='add-friend'),
    url(r'^validate-npm/$', validate_npm, name='validate-npm'),
    url(r'^delete-friend/$', delete_friend, name='delete-friend'),
    url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
    url(r'^get-friend-list-json/$', friend_list_json, name='get-friend-list-json'),
    url(r'^next-mahasiswa-list/$', next_mahasiswa_list, name='next-mahasiswa-list'),
    url(r'^prev-mahasiswa-list/$', prev_mahasiswa_list, name='prev-mahasiswa-list'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
from lab_1.views import index as index_lab1
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^$', RedirectView.as_view(url='/lab-2/', permanent = True), name = 'index'),
    url(r'^lab-3/', include(lab_3, namespace ='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    
    
]

lab_7/models.py
    # -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250, unique=True)
    added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()


def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada
    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    friend_list = Friend.objects.all()
    response = {"author": "", "mahasiswa_list": mahasiswa_list, "friend_list": friend_list}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)


def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar-teman.html'
    return render(request, html, response)

@csrf_exempt
def friend_list_json(request):
    friend = Friend.objects.all()
    data = serializers.serialize("json", friend)
    return HttpResponse(data, content_type='application/json')


@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        is_already_friend = Friend.objects.filter(npm=npm).count()
        if (is_already_friend == 0):
            friend = Friend(friend_name=name, npm=npm)
            friend.save()
            data = model_to_dict(friend)
            return HttpResponse(data)


@csrf_exempt
def delete_friend(request):
    name = request.POST['name']
    npm = request.POST['npm']
    Friend.objects.filter(npm=npm).delete()
    return HttpResponseRedirect('/lab-7/get-friend-list')


@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    num_result = Friend.objects.filter(npm=npm).count()
    data = {
        'is_taken': (num_result > 0)
    }
    return JsonResponse(data)


def model_to_dict(obj):
    data = serializers.serialize('json', [obj, ])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data


def next_mahasiswa_list(request):
    csui_helper.instance.change_direction_next_mahasiswa_list();
    return HttpResponseRedirect("/lab-7/")


def prev_mahasiswa_list(request):
    csui_helper.instance.change_direction_prev_mahasiswa_list();
    return HttpResponseRedirect("/lab-7/")

lab_7/templates/lab_7/daftar-teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> Friend List</h2> <a href="{% url 'lab-7:index' %}"> <button class="btn btn-primary btn-round ">Home </button></a><br>
                    <div id="friend-list" class="list-group">
                      {% if friend_list %}
                        {% csrf_token %}
                          <div id="all-friend"></div>
                      {% else %}
                      <div class="alert alert-danger text-center">
                        <strong>Opps!</strong> Tidak ada teman
                      </div>
                      {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
    $( document ).ready(function () {
         {# lengkapi pemanggilan ajax berikut untuk mengambil daftar teman yang ada di database #}
         $.ajax({
             method: "GET",
             url: '{% url "lab-7:get-friend-list-json" %}',
             dataType: 'json',
             success: function (data) {
                 console.log(data.length);
                 if (data.length == 0) {
                     html = '<div class="alert alert-danger text-center">' +
                             '<strong>Opps!</strong> Tidak ada teman' +
                         +'</div>';
                     $("#all-friend").append(html);
                 }
                 else {
                     console.log(data)
                     for (var key in data){
                     console.log(key);
                     var buttonDelete = '<span class="btn btn-default btn-danger" onClick="deleteFriend('+ "'" + data[key].fields.friend_name + "'"
                         + ', '+ "'" + data[key].fields.npm + "'" + ');"'+ 'style="float: right; margin-left: 5px;"'+'>Delete</span>';
                     html = '<a class="list-group-item clearfix" '+ 'id='+ data[key].fields.npm + '>' +
                         data[key].fields.friend_name + " (" + data[key].fields.npm + ")"+ buttonDelete +
                         '</a>';
                     $("#all-friend").append(html);
                     }
                 }

             },
             error: function(error){
                 alert("Data gagal diterima");
                 html = '<div class="alert alert-danger text-center">' +
                             '<strong>Opps!</strong> Tidak ada teman' +
                         +'</div>';
                 $("#all-friend").append(html);
             }
         });
     });
     var deleteFriend = function(nama, npm) {
           $.ajax({
               method: "POST",
               url: '{% url "lab-7:delete-friend" %}',
               data: { name: nama, npm: npm},
               success : function (response) {
                   $("#" + npm).remove()
               },
               error : function (error) {
                   alert("Mahasiswa tersebut tidak ada");
               }
           });
        };


    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                                    <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}');">
                                        Tambah sebagai teman
                                    </span>
                                </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                        <div class="list-group-item clearfix">
                            <a href='/lab-7/prev-mahasiswa-list/'>prev</a>
                            <a href='/lab-7/next-mahasiswa-list/' style="float: right;">next</a>
                        </div>
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                    <div class="kosong">
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman</div>
                    </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">NPM:</label>
                    <input id="field_npm" required="required" type="text" name="npm" class="form-control"/>
                    <label for="field_name">Nama</label>
                    <input id="field_name" required="required" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
                <a href="/lab-7/get-friend-list/"><button style="margin-top: 40px;">Lihat Daftar Teman</button></a>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:add-friend" %}',
            data: { name: nama, npm: npm},
            dataType: 'json',
            success : function (friend) {
                html = '<a class="list-group-item clearfix">' +
                    friend.friend_name + " (" + friend.npm + ")" +
                    '</a>';
                $(".kosong").remove();
                $("#friend-list").append(html);
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    $("#add-friend").on("submit", function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()

       $("#field_name").val("");
       $("#field_npm").val(""); 
        addFriend(name, npm)
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm,
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                     $("#field_npm").val("");
                }
            }
        });
    });
</script>
{% endblock %}